-include local.mk
RBOOT_ARGS ?=

PROGRAM = light_switch
COMPONENTS_DIR = $(PROGRAM_DIR)components
EXTRA_COMPONENTS = \
	$(COMPONENTS_DIR)/bootloader 	\
	$(COMPONENTS_DIR)/tftp_vfs 		\
	$(COMPONENTS_DIR)/ota_update 	\
	$(COMPONENTS_DIR)/sntp_time 	\
	$(COMPONENTS_DIR)/sunriset
EXTRA_CFLAGS = -D _GNU_SOURCE
PROGRAM_CFLAGS = $(CFLAGS) \
	-D SNTP_MAX_SERVERS=$(SNTP_MAX_SERVERS) \
	-D SNTP_SERVERS=$(SNTP_SERVERS) \
	-D LATITUDE=$(LATITUDE) \
	-D LONGITUDE=$(LONGITUDE) \
	-D TIMEZONE=$(TIMEZONE) \
	-D LED_PIN=$(LED_PIN) \
	-D RELAY_PIN=$(RELAY_PIN) \
	-D MORNING_LIGHTS_ON_HOURS=$(MORNING_LIGHTS_ON_HOURS) \
	-D MORNING_LIGHTS_ON_MIN=$(MORNING_LIGHTS_ON_MIN) \
	-D MIN_MORNING_LIGHTS=$(MIN_MORNING_LIGHTS) \
	-D NIGHT_LIGHTS_OFF_HOURS=$(NIGHT_LIGHTS_OFF_HOURS) \
	-D NIGHT_LIGHTS_OFF_MIN=$(NIGHT_LIGHTS_OFF_MIN)
LIBS = hal m
include $(ESP_OPEN_RTOS_DIR)/common.mk

ota_update: $(FW_FILE)
	tftp -m binary $(DEVICE_IP) -c put $(FW_FILE) $$(md5sum $(FW_FILE) | cut -d ' ' -f 1)
